name = "api"
main = "../build/worker.mjs"
# main = "../src/index.ts"
compatibility_date = "2023-12-06"
node_compat = true
workers_dev = true
[build]
command = "pnpm build"
[site]
bucket = "../../ui/build/client"
[dev]
port = 3000
ip = "0.0.0.0"
[vars]
VITE_API_URL = "http://0.0.0.0:3000"
NODE_ENV = "development"
SSR = "true"
WORKER_ENVIRONMENT = 'dev'
HOST = '0.0.0.0'
VITE_PORT = 3000
VITE_LOG_LEVEL = 'debug'
VITE_APP_NAME = 'cfw-boilerplate'
VITE_API_VERSION = '0.0.1'
VITE_UI_VERSION = '0.0.1'
VITE_APP_URL = 'http://127.0.0.1:3000'
__SECRET__ = ''
NEXTAUTH_URL = 'http://localhost:3000/api/auth'
NEXTAUTH_SECRET = 'SuperSecret'
EMAIL_SERVER_HOST = 'smtp.fastmail.com'
EMAIL_SERVER_PORT = 465
EMAIL_SERVER_USER = 'cfw-boilerplate-signups@shortpoet.com'
EMAIL_FROM = 'cfw-boilerplate-signups@shortpoet.com'
