/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./layouts/404.vue')['default']
    AdminLayout: typeof import('./layouts/AdminLayout.vue')['default']
    ApiViewer: typeof import('./components/api/ApiViewer.vue')['default']
    ApiViewerFetch: typeof import('./components/api/ApiViewerFetch.vue')['default']
    AuthLayout: typeof import('./layouts/AuthLayout.vue')['default']
    BlackLayout: typeof import('./layouts/BlackLayout.vue')['default']
    BlueLayout: typeof import('./layouts/BlueLayout.vue')['default']
    Counter: typeof import('./components/base/Counter.vue')['default']
    DropMenu: typeof import('./components/auth/DropMenu.vue')['default']
    Flash: typeof import('./components/flash/Flash.vue')['default']
    FlashMessage: typeof import('./components/flash/FlashMessage.vue')['default']
    Footer: typeof import('./components/nav/Footer.vue')['default']
    Hydrate: typeof import('./layouts/Hydrate.vue')['default']
    JsonTree: typeof import('./components/api/JsonTree.vue')['default']
    Link: typeof import('./components/nav/Link.vue')['default']
    ListViewer: typeof import('./components/api/ListViewer.vue')['default']
    ListViewerNames: typeof import('./components/api/ListViewerNames.vue')['default']
    Login: typeof import('./components/auth/Login.vue')['default']
    MainNav: typeof import('./components/nav/MainNav.vue')['default']
    PageList: typeof import('./components/pagination/PageList.vue')['default']
    PageShell: typeof import('./layouts/PageShell.vue')['default']
    Pagination: typeof import('./components/pagination/Pagination.vue')['default']
    Profile: typeof import('./components/auth/Profile.vue')['default']
    SuspenseLayout: typeof import('./layouts/SuspenseLayout.vue')['default']
    TextInput: typeof import('./components/input/TextInput.vue')['default']
    TheCounter: typeof import('./components/base/TheCounter.vue')['default']
    TheInput: typeof import('./components/input/TheInput.vue')['default']
    UserLayout: typeof import('./layouts/UserLayout.vue')['default']
  }
}
